version: "2"

services:
    db:
        image: mariadb
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: ${MYSQL_NAME}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./db_data/:/var/lib/mysql
        restart: unless-stopped
    phpmyadmin:
        image: phpmyadmin
        depends_on: 
            - db
        restart: unless-stopped
    frontend:
        image: ghcr.io/testausserveri/qrpyora/frontend
        ports:
            - 8080:80
        volumes:
            - ./static/:/usr/local/apache2/htdocs/static/
        depends_on: 
            - db
            - backend
        restart: unless-stopped
    backend:
        image: ghcr.io/testausserveri/qrpyora/backend
        environment:
            MYSQL_NAME: ${MYSQL_NAME}
            MYSQL_USERNAME: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            NOMINATIM_URL: ${NOMINATIM_URL}
            ADMIN: ${ADMIN}
        volumes:
            - ./static/:/usr/src/app/static/
        depends_on:
            - db
        restart: unless-stopped